# Generated by Django 2.2.7 on 2019-11-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='create at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified', verbose_name='modified at')),
                ('company_ruc', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('job_requeriments', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('job_location', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('website_url', models.URLField(blank=True)),
                ('job_benefits', models.TextField(blank=True)),
                ('job_urgency', models.TextField(blank=True)),
                ('job_schedule', models.TextField(blank=True)),
                ('job_comment', models.TextField(blank=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('min_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('max_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('pay_range_period', models.CharField(blank=True, choices=[('monthly', 'al mes'), ('annual', 'al año')], max_length=10, null=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
