# Generated by Django 2.2.7 on 2019-11-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='create at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified', verbose_name='modified at')),
                ('company_ruc', models.CharField(max_length=11)),
                ('company_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('requeriments', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Acepta Postulaciones', verbose_name='Application is active')),
                ('applications_made', models.PositiveIntegerField(default=0, help_text='Postulaciones realizadas', verbose_name='Aplications made')),
                ('is_verified', models.BooleanField(default=True, help_text='Determina si la oferta laboral ha sido verificada y corresponde a la empresa en mencion', verbose_name='Convocatoria verificada')),
                ('is_public', models.BooleanField(default=True, help_text='Determina si la oferta laboral es publica', verbose_name='Convocatoria publica')),
                ('show_recruiter', models.BooleanField(default=True, help_text='Mostrar al reclutador que crea la oferta laboral', verbose_name='Mostrar Reclutador')),
                ('website_url', models.URLField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('urgency', models.TextField(blank=True, null=True)),
                ('schedule', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('min_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('max_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('pay_range_period', models.CharField(blank=True, choices=[('monthly', 'al mes'), ('annual', 'al año')], max_length=10, null=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
