# Generated by Django 2.2.7 on 2019-11-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20191119_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='candidate_cellphone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
