# Generated by Django 2.2.7 on 2019-11-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20191111_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
