# Generated by Django 2.2.7 on 2019-11-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20191119_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='first_attachment',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='max_salary',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='min_salary',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='pay_range_period',
            field=models.CharField(blank=True, choices=[('monthly', 'al mes'), ('annual', 'al año')], max_length=10, null=True),
        ),
    ]
