# Generated by Django 2.2.7 on 2019-11-19 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20191119_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='company_name',
            new_name='company_area',
        ),
        migrations.AddField(
            model_name='job',
            name='company_role',
            field=models.CharField(default='Analista', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='company_sub_area',
            field=models.CharField(default='Planeamiento', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='contract_type',
            field=models.CharField(default='Permanente', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='company_ruc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.Company', to_field='ruc'),
        ),
    ]
