# Generated by Django 2.2.7 on 2019-11-20 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20191119_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='schedule',
            new_name='work_schedule',
        ),
    ]
