# Generated by Django 2.2.7 on 2019-11-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20191112_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Determina si la oferta laboral es publica', verbose_name='Convocatoria publica'),
        ),
    ]
