# Generated by Django 2.2.7 on 2019-11-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='show_recruiter',
            field=models.BooleanField(default=True, help_text='Mostrar al reclutador que crea la oferta laboral', verbose_name='Mostrar Reclutador'),
        ),
    ]
