# Generated by Django 2.2.7 on 2019-11-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_show_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_verified',
            field=models.BooleanField(default=True, help_text='Determina si la oferta laboral ha sido verificada y corresponde a la empresa en mencion', verbose_name='Convocatoria verificada'),
        ),
    ]
