# Generated by Django 2.2.7 on 2019-11-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_job_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_ruc',
            field=models.CharField(max_length=11),
        ),
    ]
