# Generated by Django 2.2.7 on 2019-11-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Set to true when the user an active account.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='jobs_applied',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='jobs_created',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
