# Generated by Django 2.2.7 on 2019-11-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_recruiter',
            field=models.BooleanField(default=False, help_text='Set to true when the user is a recruiter and can publish jobs.', verbose_name='recruiter'),
        ),
    ]
