# Generated by Django 2.2.7 on 2019-11-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191113_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Set to true when the user has an active account.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=True, help_text='Help easly distinguish users and perfom queries. Clients are the main type of user.', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Set to true when the user has verified its email adress.', verbose_name='verified'),
        ),
    ]
